# Generated by Django 4.0.3 on 2022-03-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='houserental',
            name='no_houses',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='houserental',
            name='no_vacant_houses',
            field=models.IntegerField(null=True),
        ),
    ]
