# Generated by Django 4.0.3 on 2022-03-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saka', '0002_houserental_no_houses_houserental_no_vacant_houses'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='caretakercontact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='monthlyrent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='rentalunit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='unittype',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='post',
            name='utilities',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
