# Generated by Django 4.0.3 on 2022-03-23 17:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saka', '0003_post_bedrooms_post_caretakercontact_post_monthlyrent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='houseimage',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
