# Generated by Django 4.0.3 on 2022-03-23 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saka', '0004_post_houseimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='houseimage',
            new_name='logo',
        ),
    ]
