# Generated by Django 4.0.3 on 2022-03-23 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saka', '0005_rename_houseimage_post_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='logo',
        ),
    ]
